name: Storm CMS Press Release
description: Storm CMS Press Release
recipes:
  - storm_cms_content_type_base
  - storm_cms_media
config:
  actions:
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.press_release:
          - basic
          - advanced
          - open_graph
          - twitter_cards
    workflows.workflow.editorial:
      addNodeTypes:
        - press_release
